repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: name-tests-test
  - id: trailing-whitespace
  - id: end-of-file-fixer
- repo: https://github.com/timothycrosley/isort/
  rev: 5.4.2
  hooks:
  - id: isort
- repo: https://github.com/psf/black
  rev: stable
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
  - id: flake8
    additional_dependencies: [flake8-bugbear]
- repo: https://github.com/PyCQA/pydocstyle
  rev: 5.0.2
  hooks:
  - id: pydocstyle
- repo: local  # Use local pylint and mypy hook for dynamic analysis
  hooks:
  - id: pylint
    name: pylint
    entry: pylint
    language: python
    types: [python]
  - id: mypy
    name: mypy
    entry: mypy
    language: python
    types: [python]
