name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
        pip install torch-scatter==latest+cpu -f "https://pytorch-geometric.com/whl/torch-$(python -c "import torch; print(torch.__version__)").html"
        pip install torch-sparse==latest+cpu -f https://pytorch-geometric.com/whl/torch-$(python -c "import torch; print(torch.__version__)").html
        pip install torch-cluster==latest+cpu -f https://pytorch-geometric.com/whl/torch-$(python -c "import torch; print(torch.__version__)").html
        pip install torch-spline-conv==latest+cpu -f https://pytorch-geometric.com/whl/torch-$(python -c "import torch; print(torch.__version__)").html
        pip install -r requirements.txt
    - name: Run pre-commit hook
      run: |
        pre-commit run --all-files
    - name: Run unit tests
      run: |
        make test
