name: tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install cuda-10–2
        sudo apt install libcudnn7
        python -m pip install --upgrade pip
        make install
    - name: Run pre-commit hook
      run: |
        pre-commit run --all-files
    - name: Run unit tests
      run: |
        make test
